---
version: '3.3'

services:

  cassandra:
    container_name: cassandra
    image: cassandra
    ports:
      - 9042:9042
    volumes:
      - ./cassandra/config/cassandra.yaml:/etc/cassandra/cassandra.yaml
    network_mode: host
