{
 "title": "SPEED",
 "time": { "from": "2020-12-07T01:12:18.403Z", "to": "2020-12-07T01:42:18.403Z" },
 "panels": [
  {
   "title": "actor messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "actorA_messages" },
    { "expr": "actorB_messages" },
    { "expr": "actorC_messages" },
    { "expr": "actorD_messages" }
   ]
  },
  {
   "title": "eventual_consistency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "OptimalBatcher_RocksdbBatchInserterbuffer_time / 1000",
     "legendFormat": "buffer_time"
    },
    {
     "expr": "OptimalBatcher_RocksdbBatchInserterbuffer_size / 1000",
     "legendFormat": "buffer size"
    }
   ]
  },
  {
   "title": "events_read_from_cassandra",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "events_read_from_cassandra", "legendFormat": "total" },
    {
     "expr": "sum(increase(events_read_from_cassandra[1m]))",
     "legendFormat": "per minute"
    }
   ]
  },
  {
   "title": "events_saved_to_cassandra",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "events_saved_to_cassandra", "legendFormat": "total" },
    {
     "expr": "sum(increase(events_saved_to_cassandra[1m]))",
     "legendFormat": "per minute"
    }
   ]
  },
  {
   "title": "messages_published_to_kafka",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "messages_published_to_kafka", "legendFormat": "total" },
    {
     "expr": "sum(increase(messages_published_to_kafka[1m]))",
     "legendFormat": "per minute"
    }
   ]
  },
  {
   "title": "messages_processed_by_actor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "messages_processed_by_actor", "legendFormat": "total" },
    {
     "expr": "sum(increase(messages_processed_by_actor[1m]))",
     "legendFormat": "per minute"
    }
   ]
  },
  {
   "title": "events_read_from_rocksdb",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "events_read_from_rocksdb", "legendFormat": "total" },
    {
     "expr": "sum(increase(events_read_from_rocksdb[1m]))",
     "legendFormat": "per minute"
    }
   ]
  },
  {
   "title": "events_saved_to_rocksdb",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "events_saved_to_rocksdb", "legendFormat": "total" },
    {
     "expr": "sum(increase(events_saved_to_rocksdb[1m]))",
     "legendFormat": "per minute"
    }
   ]
  }
 ]
}